FROM  markhobson/maven-chrome:latest

WORKDIR /app

COPY . .

#RUN sed -i 's/chromedriver = C:\/\/driver83\/\/chromedriver.exe/chromedriver =\/usr\/bin\/chromedriver/g' configs/properties
#VOLUME  "./reports:/app/reports" 

CMD mvn clean compile test-compile